using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;

using Microsoft.Extensions.AI;

using Shellvis.Core.Config;
using Shellvis.Core.Tools;

using YamlDotNet.Serialization;
using YamlDotNet.Serialization.NamingConventions;

namespace Shellvis.Core.Connectors;

/// <summary>What became of one connector package.</summary>
/// <param name="Name">The connector, named as it was found.</param>
/// <param name="Ready">Whether its tools are registered and callable.</param>
/// <param name="ToolCount">How many tools it contributed.</param>
/// <param name="Detail">
/// Why, in a sentence. Said even when everything worked, because "not configured" and
/// "refused" have to be distinguishable at a glance from "loaded".
/// </param>
public sealed record ConnectorStatus(string Name, bool Ready, int ToolCount, string Detail);

/// <summary>
/// Finding connector packages, checking them, and turning them into tools.
///
/// <b>A package is content, not code the user wrote.</b> A connector directory can be
/// downloaded, copied from a colleague or generated by a model, and everything in it ends up
/// somewhere privileged: descriptions go into the system prompt, tool names into the model's
/// vocabulary, paths into requests carrying the user's credentials. So the loader applies
/// four rules that no manifest can talk its way out of:
///
/// <list type="number">
/// <item><b>A manifest holding something that looks like a credential is refused whole.</b>
/// Not stripped -- the same reasoning as <c>SkillWriter</c>: quietly removing part of a file
/// leaves something that still looks complete, and the person who wrote it never learns.</item>
/// <item><b>Only a GET can be read-only.</b> A manifest declaring <c>effect: read</c> on a
/// POST is describing its own harmlessness, which is exactly what a malicious one would do.
/// The same reason MCP's <c>trustReadOnly</c> lives in the local config.</item>
/// <item><b>A built-in tool always wins.</b> Names are prefixed, and a collision is skipped
/// rather than overwritten, so no package can put itself in front of <c>powershell_run</c>.</item>
/// <item><b>Descriptions run through the injection check</b> the MCP host uses, because they
/// land in the system prompt exactly as a remote tool's description does.</item>
/// </list>
///
/// A connector that fails any of these is reported and skipped. One bad package must not stop
/// the others from loading, for the same reason one unreachable MCP server does not stop the
/// agent from starting.
/// </summary>
public sealed class ConnectorLoader(ToolRegistry registry)
{
    /// <summary>
    /// Patterns that mean "this file is carrying a secret".
    ///
    /// Deliberately blunt. A false positive costs someone a rename in their own manifest and
    /// says exactly why; a false negative puts a password in a file that gets copied between
    /// machines, quoted in error messages and shown in an install prompt.
    /// </summary>
    private static readonly Regex[] CredentialPatterns =
    [
        // A value assigned to a credential-shaped key. ${VAR} and an empty value are fine:
        // those are the forms the rules require.
        //
        // 'secret' is deliberately absent from this list even though it is the most
        // credential-shaped word here: it is a field of the schema whose value is a NAME by
        // contract, and flagging it would refuse every correctly written manifest. What
        // keeps a password out of it is the name-shape check in ConnectorManifest.Validate,
        // which a real password fails.
        new(@"(?im)^\s*(password|passwd|pwd|token|apikey|api_key|credential)\s*:\s*(?!\s*$)(?!\$\{)\S",
            RegexOptions.Compiled),

        // A ready-made Authorization header. The point of the manifest is that it cannot
        // hold one; someone pasting a working curl command finds out here.
        new(@"(?i)authorization\s*:\s*(basic|bearer)\s+\S", RegexOptions.Compiled),

        // user:password inside a url.
        new(@"(?i)https?://[^/\s:@]+:[^/\s@]+@", RegexOptions.Compiled),
    ];

    private static readonly string[] InjectionMarkers =
    [
        "ignore previous", "ignore all previous", "disregard the above",
        "system prompt", "you are now", "new instructions",
        "do not tell the user", "without telling the user", "without asking",
    ];

    private static readonly Regex UnsafeNameChars = new(@"[^A-Za-z0-9_]", RegexOptions.Compiled);

    private readonly List<ConnectorStatus> _status = [];
    private readonly List<HttpConnector> _live = [];

    /// <summary>What every package found so far turned into.</summary>
    public IReadOnlyList<ConnectorStatus> Status => _status;

    /// <summary>
    /// The directories connectors are read from, user first.
    ///
    /// Same order and same reason as the skills: what ships is a default, and a package of
    /// the user's own with the same name wins over it.
    /// </summary>
    public static IEnumerable<string> Directories()
    {
        yield return ShellvisPaths.ConnectorsDirectory;
        yield return ShellvisPaths.BundledConnectorsDirectory;
    }

    /// <summary>Load every connector found, and register the tools of those that are configured.</summary>
    public IReadOnlyList<ConnectorStatus> LoadAll()
    {
        var seen = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

        foreach (string root in Directories())
        {
            if (!System.IO.Directory.Exists(root))
                continue;

            foreach (string directory in System.IO.Directory.EnumerateDirectories(root))
            {
                string file = Path.Combine(directory, "connector.yaml");

                if (!File.Exists(file))
                    continue;

                // The user's copy already won; the bundled one is not a second connector.
                if (!seen.Add(Path.GetFileName(directory)))
                    continue;

                _status.Add(Load(file));
            }
        }

        return _status;
    }

    /// <summary>Read, check and register one manifest file.</summary>
    public ConnectorStatus Load(string file)
    {
        string name = Path.GetFileName(Path.GetDirectoryName(file)) ?? "connector";
        string text;

        try
        {
            text = File.ReadAllText(file, Encoding.UTF8);
        }
        catch (IOException ex)
        {
            return new ConnectorStatus(name, false, 0, $"could not be read: {ex.Message}");
        }

        if (FindCredential(text) is { } pattern)
        {
            return new ConnectorStatus(name, false, 0,
                $"refused: the manifest appears to contain a credential ({pattern}). "
                + "A connector names a variable and never holds its value.");
        }

        ConnectorManifest manifest;

        try
        {
            manifest = new DeserializerBuilder()
                .WithNamingConvention(CamelCaseNamingConvention.Instance)
                .IgnoreUnmatchedProperties()
                .Build()
                .Deserialize<ConnectorManifest>(text) ?? new ConnectorManifest();
        }
        catch (YamlDotNet.Core.YamlException ex)
        {
            // The line number is the whole value of this message: a manifest is hand-written.
            return new ConnectorStatus(name, false, 0,
                $"is not valid YAML at line {ex.Start.Line}: {ex.Message}");
        }

        if (string.IsNullOrWhiteSpace(manifest.Name))
            manifest.Name = name;

        manifest.Directory = Path.GetDirectoryName(file) ?? string.Empty;

        if (manifest.Validate() is { } problem)
            return new ConnectorStatus(manifest.Name, false, 0, problem);

        if (manifest.Kind == ConnectorKind.Mcp)
        {
            // Handed on rather than run here. The MCP host already has the transports, the
            // namespacing, the injection check and the scrubbed child environment; a second
            // implementation of any of that would be a second set of security rules to keep
            // in step.
            return new ConnectorStatus(manifest.Name, false, 0,
                "is an mcp connector; start it through the mcpServers section of config.yaml.");
        }

        return Register(manifest);
    }

    private ConnectorStatus Register(ConnectorManifest manifest)
    {
        HttpConnector? connector = HttpConnector.TryCreate(manifest, out string? reason);

        if (connector is null)
        {
            // No tools at all rather than tools that fail on first use: a model that is told
            // it can search Jira plans around that, spends a round finding out it cannot, and
            // reads as broken rather than as unconfigured.
            return new ConnectorStatus(manifest.Name, false, 0,
                reason ?? "is not configured on this machine.");
        }

        _live.Add(connector);

        string prefix = Prefix(manifest.Name);
        var warnings = new List<string>();
        int registered = 0;

        foreach (ConnectorTool tool in manifest.Tools)
        {
            string toolName = ToolName(prefix, tool.Name);

            if (registry.Find(toolName) is not null)
            {
                warnings.Add($"'{tool.Name}' skipped, the name {toolName} is taken");
                continue;
            }

            if (FindInjection(tool.Description) is { } marker)
            {
                warnings.Add($"'{tool.Name}' refused, its description contains \"{marker}\"");
                continue;
            }

            // The floor, not the claim. Only a GET may end up silent.
            SideEffect effect =
                tool.Method.Equals("GET", StringComparison.OrdinalIgnoreCase)
                && tool.Effect.Equals("read", StringComparison.OrdinalIgnoreCase)
                    ? SideEffect.ReadOnly
                    : SideEffect.Mutating;

            if (effect == SideEffect.Mutating
                && tool.Effect.Equals("read", StringComparison.OrdinalIgnoreCase))
            {
                // Said out loud rather than fixed in silence. A manifest that claims a POST is
                // read-only is either wrong or trying something, and both are worth knowing.
                warnings.Add($"'{tool.Name}' claims read but is a {tool.Method.ToUpperInvariant()}; it will ask");
            }

            try
            {
                registry.RegisterFunction(
                    new ConnectorFunction(connector, tool, toolName),
                    effect,
                    toolName,
                    previewParameter: tool.Preview ?? tool.Params.FirstOrDefault()?.Name,
                    glyph: "plug");

                registered++;
            }
            catch (InvalidOperationException ex)
            {
                warnings.Add($"'{tool.Name}' skipped: {ex.Message}");
            }
        }

        string detail = warnings.Count == 0
            ? $"{registered} tool(s)"
            : $"{registered} tool(s); " + string.Join("; ", warnings);

        return new ConnectorStatus(manifest.Name, registered > 0, registered, detail);
    }

    /// <summary>The namespace a connector's tools live in.</summary>
    /// <remarks>
    /// A tool that already begins with its connector's name keeps the name it was given:
    /// <c>jira_search</c> in the <c>jira</c> connector stays <c>jira_search</c> rather than
    /// becoming <c>jira_jira_search</c>. The guarantee that matters -- that a package cannot
    /// shadow a built-in -- comes from the collision check, not from the spelling.
    /// </remarks>
    private static string Prefix(string connectorName)
    {
        string sanitised = UnsafeNameChars.Replace(connectorName, "_").Trim('_');

        // A vendor-prefixed package name reads as "atlassian_jira_jira_search" otherwise.
        // The last segment is the one that names the system.
        int lastPart = sanitised.LastIndexOf('_');

        return lastPart >= 0 ? sanitised[(lastPart + 1)..] : sanitised;
    }

    private static string ToolName(string prefix, string toolName)
    {
        string sanitised = UnsafeNameChars.Replace(toolName, "_");

        return sanitised.StartsWith(prefix + "_", StringComparison.OrdinalIgnoreCase)
            ? sanitised
            : $"{prefix}_{sanitised}";
    }

    /// <summary>Which credential pattern the text matched, described in words.</summary>
    public static string? FindCredential(string text)
    {
        if (CredentialPatterns[0].IsMatch(text))
            return "a password or token with a literal value";

        if (CredentialPatterns[1].IsMatch(text))
            return "a ready-made Authorization header";

        return CredentialPatterns[2].IsMatch(text) ? "a url with a password in it" : null;
    }

    /// <summary>Which injection marker a description carries, or null.</summary>
    public static string? FindInjection(string? description)
    {
        if (string.IsNullOrWhiteSpace(description))
            return null;

        string lowered = description.ToLowerInvariant();

        return InjectionMarkers.FirstOrDefault(
            marker => lowered.Contains(marker, StringComparison.Ordinal));
    }

    /// <summary>Release the HTTP clients of every loaded connector.</summary>
    public void Dispose()
    {
        foreach (HttpConnector connector in _live)
            connector.Dispose();

        _live.Clear();
    }
}

/// <summary>
/// One declared tool, as the model sees it.
///
/// The schema is built here rather than generated from a C# signature, because there is no
/// signature: the parameters come out of a YAML file. Everything is a string on purpose --
/// a REST call sends text either way, and a declared type would be a second thing that can
/// disagree with the API.
/// </summary>
internal sealed class ConnectorFunction(HttpConnector connector, ConnectorTool tool, string name)
    : AIFunction
{
    public override string Name { get; } = name;

    public override string Description { get; } = tool.Description ?? $"Calls {tool.Name}.";

    public override JsonElement JsonSchema { get; } = BuildSchema(tool);

    protected override async ValueTask<object?> InvokeCoreAsync(
        AIFunctionArguments arguments, CancellationToken cancellationToken)
    {
        return await connector.CallAsync(tool, arguments, cancellationToken).ConfigureAwait(false);
    }

    private static JsonElement BuildSchema(ConnectorTool tool)
    {
        var properties = new Dictionary<string, object>(StringComparer.Ordinal);
        var required = new List<string>();

        foreach (ConnectorParameter parameter in tool.Params)
        {
            properties[parameter.Name] = new Dictionary<string, object>(StringComparer.Ordinal)
            {
                ["type"] = "string",
                ["description"] = parameter.Description ?? parameter.Name,
            };

            if (parameter.Required)
                required.Add(parameter.Name);
        }

        var schema = new Dictionary<string, object>(StringComparer.Ordinal)
        {
            ["type"] = "object",
            ["properties"] = properties,
            ["required"] = required,
        };

        return JsonSerializer.SerializeToElement(schema);
    }
}
